### ISSUE TITLE
Checkbox inside CellList

### ISSUE THREAD

**Issue by doctorj** [mgwt/mgwt#285]
After more than a year I fetched and merged and after that I noticed strange behavior with my CellLists that render checkboxes inside them.
Check box needs to be tapped twice to change, although my code adds/removes checked attribute successfully.  Other CellList acts even less predictable, I couldnt find a pattern when checkbox is rendered as checked/unchecked after a tap.
Anyway, after a little bit of investigation, I found out that change introduced in commit 26a0258 is to blame. This is the code that was removed:
```
      // if windows phone then do not prevent default, causes scrolling issues when
      // in scroll panel (not sure why), ie10 desktop is fine
      if (!MGWT.getOsDetection().isWindowsPhone())
      {
        event.preventDefault();
      }
```
Before that, in commit 24aa01f
```
event.preventDefault();
```
was replaced with that code.

Commit message says that "preventDefault breaks native scrolling by obviously preventing the default behaviour which is to sroll the list", but I havent noticed any problems with scrolling (at least not on android device)

**Comment by paulfrench** [comment]
Looking at the history of the CellList.java file we have effectively removed event.preventDefault(). The reason was at the time if you call preventDefault on a touchstart then you did not get any *native* scrolling (i.e. a scrollable div). A fair bit of event handling has changed to cater for devices that can do touch and mouse simultaneously so maybe something needs re-visting. I'll take a look when I get a chance.

Any chance of a "as simple as possible" test case demonstrating the issue. Possibly adding a few lines to the showcase app?

or... if you could give me some clear instructions what to setup to show the issue.

Thanks

**Comment by doctorj** [comment]
Here is a samle project (GWT 2.7.0):
https://github.com/doctorj/mgwt-test

While building this sample project at first I couldn't reproduce issue, until I added TouchDelegate for list element. Maybe that helps.
In this sample project there are four columns of checkboxes and all of them are checked. First tap never unchecks (although checked attribute is removed from INPUT element). After that every 4th, 5th tap does not uncheck.

Thanks

**Comment by paulfrench** [comment]
Brilliant, hopefully will take a look tonight

**Comment by paulfrench** [comment]
Hello doctorj, Works fine for me. I only tested in desktop chrome. What browser and device are you using? I get a full screen of cell items each with 4 checkboxes all checked. The screen does not scroll. I can check and uncheck all the checkboxes without issue.

Are you using the latest code from mgwt/mgwt repo ?

Cheers

**Comment by doctorj** [comment]
Hello paulfrench,
I'm testing in Chrome 52 / Windows 7, using latest code from mgwt/mgwt repo.
Screen does not scroll because MGWTTest.gwt.xml restricts number of permutations (does not include desktop).
Anyway, the problem is with mobile. Here is how to reproduce the isssue:
- compile
- open chrome
- open developer tools (F12)
- press toggle device toolbar button (Ctrl+Shift+M)
- open page

Thanks

**Comment by paulfrench** [comment]
Still works for me. I've taken out your forced permutation and I'm using super dev mode so it will compile the required permutation for whatever device I am running on.

However I have looked at your code and something looks odd to me. Why are you removing the checked attribute yourself on a tap?

The default behaviour for a checkbox is to check and uncheck itself when clicked or tapped. Just take out that code

					
					if (element.hasAttribute("checked"))
						element.removeAttribute("checked");
					else
						element.setAttribute("checked", "");
					
				}
`
Thinking about it the reason why this code would have worked without issue in the past was because preventDefault being called on the touch start event in the cell list stops the default checkbox behaviour of being checked and unchecked.

We avoid doing preventDefault on events without good reason so certain default behaviours of the browser still work as expected e.g. scrolling text area, cut and paste etc

**Comment by doctorj** [comment]
You are right, me adding/removing checked attribute creates this mess.
But... Yes, default behaviour for a checkbox is to check and uncheck itself when clicked or tapped, but here's how browsers work: they render box as checked/unchecked, but they do not add/remove attribute, so at the end I have a bunch of checkboxes that are unchecked but that still have attribute "checked" and I have no way to know what has been checked/unchecked.
The other reason I add/remove attributes myself is that when user "misses" checkbox with his finger, and taps very close to it on the surrounding DIV or even LI element, I want to "count" it as hit, so I set attribute myself. When I do that browser renders it correctly.
So, for me the best is to prevent default and do it all myself. Of course, I don't think we should change code because of my use case.
Thanks a lot for trying to help me, but since you can't even reproduce issue, and since I have everything working by changing code in CellList, I think I should stop wasting your time with this one and close this issue. Agree?

**Comment by paulfrench** [comment]
Agreed! Would it not be better you add a touch start handler to your listDelegate and do the preventDefault there. Saves modifying the CellList code. Up to you. Cheers.

**Comment by doctorj** [comment]
Will do that.
Thank you.
